server:
  port: 8080

spring:
  application:
    name: ai-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    redis:
      host: 127.0.0.1
      port: 6379
    gateway:
      routes:
        - id: user-service
          uri: lb://ai-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: character-service
          uri: lb://ai-character-service
          predicates:
            - Path=/api/character/**
          filters:
            - StripPrefix=2
        - id: chat-service
          uri: lb://ai-chat-service
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=2
        - id: voice-service
          uri: lb://ai-voice-service
          predicates:
            - Path=/api/voice/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: qiniuyun_ai_gateway${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"



